package com.yowyob_access.access.mapper;

import com.yowyob_access.access.DTO.role.CreateRoleRequest;
import com.yowyob_access.access.DTO.role.RoleDto;
import com.yowyob_access.access.entities.Role;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

/**
 *   Component that converts between Role entity and Role DTOs.
 *   - toDto(Role) converts entity -> DTO (hides sensitive fields).
 *   - toEntity(CreateRoleRequest, tenantId) converts request -> entity.
 *   - joinPermissions(List<String>) and splitPermissions(String) convert between
 *     List and CSV representation used in the Role entity.
 */
@Component
public class RoleMapper {

    private static final String CSV_SEPARATOR = ",";

   
    public RoleDto toDto(Role role) {
        if (role == null) {
            return null;
        }

        RoleDto dto = new RoleDto();
        dto.setId(role.getId());
        dto.setName(role.getName());
        dto.setDescription(role.getDescription());
        dto.setPermissions(splitPermissions(role.getPermissions()));

        // Convert Instant -> LocalDateTime for DTO
        Instant createdInstant = role.getCreatedAt();
        if (createdInstant != null) {
            dto.setCreatedAt(LocalDateTime.ofInstant(createdInstant, ZoneId.systemDefault()));
        }

        Instant modifiedInstant = role.getModifiedAt();
        if (modifiedInstant != null) {
            dto.setModifiedAt(LocalDateTime.ofInstant(modifiedInstant, ZoneId.systemDefault()));
        }

        return dto;
    }

 
    public Role toEntity(CreateRoleRequest req, String tenantId) {
        if (req == null) {
            return null;
        }

        Role r = new Role();

        // id is generated by entity default (UUID) or by DB depending on mapping.
        r.setTenantId(tenantId);
        r.setName(req.getName());
        r.setDescription(req.getDescription());
        r.setPermissions(joinPermissions(req.getPermissions()));

        // default flags / timestamps are set by service before save
        return r;
    }

 
    public String joinPermissions(List<String> permissions) {
        if (permissions == null || permissions.isEmpty()) {
            return "";
        }
        return permissions.stream()
            .filter(Objects::nonNull)
            .map(String::trim)
            .filter(s -> !s.isEmpty())
            .collect(Collectors.joining(CSV_SEPARATOR));
    }

    public List<String> splitPermissions(String csv) {
        if (csv == null || csv.isBlank()) {
            return Collections.emptyList();
        }
        return List.of(csv.split(CSV_SEPARATOR)).stream()
            .map(String::trim)
            .filter(s -> !s.isEmpty())
            .collect(Collectors.toList());
    }
}
